// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
   
    {
      type: 'category',
      label: 'Sensorización, infraestructuras y tecnologías de datos', 
      items: ['Sensorización, infraestructuras y tecnologías de datos/Introducción',
              'Sensorización, infraestructuras y tecnologías de datos/DataSets',
              'Sensorización, infraestructuras y tecnologías de datos/Packages'
      ],
    },
    {
      type: 'category',
      label: 'Observación de la Tierra y el clima',
      items: ['Observación de la Tierra y el clima/Introducción'],
    },
    {
      type: 'category',
      label: 'Eficiencias en el uso del suelo, ambiente, insumos y estilos de agricultura',
      items: ['Eficiencias en el uso del suelo, ambiente, insumos y estilos de agricultura/Introducción'],
    },    
    {
      type: 'category',
      label: 'Optimización de agua y energía',
      items: ['Optimización de agua y energía/Introducción'],
    }, 
    {
      type: 'category',
      label: 'Gestión pre y postcosecha e industria alimentaria',
      items: ['Gestión pre y postcosecha e industria alimentaria/Introducción'],
    }, 
    {
      type: 'category',
      label: 'Competencia de paises terceros en el mercado de cítricos',
      items: ['Competencia de paises terceros en el mercado de cítricos/Introducción'],
    }, 
    {
      type: 'category',
      label: 'Gobernanza y desarrollo de oportunidades de negocio y utilidades',
      items: ['Gobernanza y desarrollo de oportunidades de negocio y utilidades/Introducción'],
    }, 



  ],

};

export default sidebars;
